#数据源配置
spring:
  redis:
    ##redis 单机环境配置
    host: 192.168.88.134
    port: 6379
    password:
    database: 0
    ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: 192.168.88.134:7001,192.168.88.134:7002,192.168.88.134:7003
    #  commandTimeout: 5000
  datasource:
    url: jdbc:mysql://192.168.88.134:3306/blade?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#第三方登陆
social:
  enabled: true
  domain: http://192.168.88.134:1888

#blade配置
blade:
  prop:
    upload-domain: http://192.168.88.134:8888
    remote-mode: true
    remote-path: /usr/share/nginx/html
    remote-path-iis: D://iis/html
    log-mode: true
